import Patient, { type IPatient } from "../models/Patient";
import Visit from "../models/Visit";
import Prescription from "../models/Prescription";
import type { Types } from "mongoose";

const mapPatient = (patient: IPatient) => ({
  id: patient._id.toString(),
  patientId: patient.patientId,
  name: patient.name,
  age: patient.age,
  dateOfBirth: patient.dateOfBirth,
  gender: patient.gender,
  phone: patient.phone,
  address: patient.address,
  allergies: patient.allergies,
  notes: patient.notes,
  createdAt: patient.createdAt,
  updatedAt: patient.updatedAt,
});

export interface CreatePatientData {
  userId: Types.ObjectId;
  name: string;
  age: number;
  dateOfBirth?: string;
  gender: "male" | "female" | "other";
  phone: string;
  address: string;
  allergies?: string;
  notes?: string;
}

export interface UpdatePatientData {
  name?: string;
  age?: number;
  dateOfBirth?: string;
  gender?: "male" | "female" | "other";
  phone?: string;
  address?: string;
  allergies?: string;
  notes?: string;
};

/**
 * Generate the next patient ID for a specific doctor's account.
 *
 * Patient IDs are unique within each doctor's account.
 *
 * Example:
 *
 * Doctor A:
 * PAT-001
 * PAT-002
 * PAT-003
 *
 * Doctor B:
 * PAT-001
 * PAT-002
 *
 * The same patient ID can therefore exist for different doctors.
 */
const generatePatientId = async (
  userId: Types.ObjectId,
): Promise<string> => {
  const lastPatient = await Patient.findOne({
    userId,
    patientId: /^PAT-\d+$/,
  })
    .sort({ patientId: -1 })
    .select("patientId")
    .lean();

  if (!lastPatient) {
    return "PAT-001";
  }

  const match = lastPatient.patientId.match(/^PAT-(\d+)$/);

  if (!match) {
    return "PAT-001";
  }

  const nextNumber = Number(match[1]) + 1;

  return `PAT-${String(nextNumber).padStart(3, "0")}`;
};

/**
 * Create a new patient.
 *
 * The patient ID is generated by the backend.
 * The client cannot choose or override the patient ID.
 */
export const createPatient = async (
  data: CreatePatientData,
) => {
  const patientId = await generatePatientId(data.userId);

  const patient = await Patient.create({
    userId: data.userId,
    patientId,
    name: data.name,
    age: data.age,
    dateOfBirth: data.dateOfBirth,
    gender: data.gender,
    phone: data.phone,
    address: data.address,
    allergies: data.allergies ?? "",
    notes: data.notes ?? "",
  });

  return mapPatient(patient);
};

/**
 * Get all patients belonging to the authenticated doctor.
 */
export const getAllPatients = async (
  userId: Types.ObjectId,
) => {
  const patients = await Patient.find({
    userId,
  }).sort({
    createdAt: -1,
  });

  return patients.map(mapPatient);
};

/**
 * Get one patient belonging to the authenticated doctor.
 */
export const getPatientById = async (
  userId: Types.ObjectId,
  id: string,
) => {
  const patient = await Patient.findOne({
    _id: id,
    userId,
  });

  if (!patient) {
    return null;
  }

  return mapPatient(patient);
};

/**
 * Update a patient.
 *
 * Patient ID and user ownership cannot be changed.
 */
export const updatePatient = async (
  userId: Types.ObjectId,
  id: string,
  data: UpdatePatientData,
) => {
  const patient = await Patient.findOneAndUpdate(
    {
      _id: id,
      userId,
    },
    data,
    {
      new: true,
      runValidators: true,
    },
  );

  if (!patient) {
    return null;
  }

  return mapPatient(patient);
};

/**
 * Delete a patient and all related visits and prescriptions.
 */
export const deletePatient = async (
  userId: Types.ObjectId,
  id: string,
) => {
  const patient = await Patient.findOne({
    _id: id,
    userId,
  });

  if (!patient) {
    return null;
  }

  // Delete prescriptions belonging to this patient.
  await Prescription.deleteMany({
    patientId: patient._id,
  });

  // Delete visits belonging to this patient.
  await Visit.deleteMany({
    patientId: patient._id,
  });

  // Delete the patient itself.
  await Patient.findOneAndDelete({
    _id: id,
    userId,
  });

  return mapPatient(patient);
};