import { z } from "zod";

const patientFields = {
  name: z
    .string()
    .trim()
    .min(2, "Patient name must be at least 2 characters long.")
    .max(150, "Patient name must not exceed 150 characters."),

  age: z
    .number()
    .int("Age must be a whole number.")
    .min(0, "Age cannot be negative.")
    .max(150, "Please provide a valid age."),

  dateOfBirth: z
    .string()
    .trim()
    .max(20, "Date of birth is invalid.")
    .optional(),

  gender: z.enum(["male", "female", "other"], {
    message: "Please select a valid gender.",
  }),

  phone: z
    .string()
    .trim()
    .refine(
      (value) => {
        // Empty phone is allowed because the field is optional.
        if (value === "") {
          return true;
        }

        const normalized = value.replace(/[\s-]/g, "");

        return /^(?:\+8801|8801|01)\d{9}$/.test(normalized);
      },
      {
        message: "Please enter a valid Bangladesh mobile number.",
      },
    )
    .optional(),

  address: z
    .string()
    .trim()
    .max(500, "Address must not exceed 500 characters.")
    .optional(),

  allergies: z
    .string()
    .trim()
    .max(1000, "Allergy information must not exceed 1000 characters.")
    .optional(),

  notes: z
    .string()
    .trim()
    .max(2000, "Notes must not exceed 2000 characters.")
    .optional(),
};

/**
 * Create patient validation.
 *
 * Required:
 * - name
 * - age
 * - gender
 *
 * Optional:
 * - dateOfBirth
 * - phone
 * - address
 * - allergies
 * - notes
 *
 * patientId is generated by the backend.
 * userId is taken from the authenticated user.
 */
export const createPatientSchema = z.object({
  name: patientFields.name,

  age: patientFields.age,

  dateOfBirth: patientFields.dateOfBirth,

  gender: patientFields.gender,

  phone: patientFields.phone,

  address: patientFields.address,

  allergies: patientFields.allergies,

  notes: patientFields.notes,
});

/**
 * Update patient validation.
 *
 * All patient fields are optional during update.
 *
 * Patient ID cannot be changed.
 */
export const updatePatientSchema = z
  .object({
    name: patientFields.name.optional(),

    age: patientFields.age.optional(),

    dateOfBirth: patientFields.dateOfBirth.optional(),

    gender: patientFields.gender.optional(),

    phone: patientFields.phone,

    address: patientFields.address,

    allergies: patientFields.allergies,

    notes: patientFields.notes,
  })
  .strict();

export type CreatePatientInput = z.infer<typeof createPatientSchema>;

export type UpdatePatientInput = z.infer<typeof updatePatientSchema>;
